Repository elastic/ecs-logging-ruby, pull requests merged in 2020-12, with the labels that each got.

#4 [CI] Enable multibranch pipeline
  .ci/Jenkinsfile
  .ci/install-rbenv.sh
  .gitignore
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  bin/dev
  docker-compose.yml
  docker/entrypoint.sh
  spec/spec_helper.rb
  vendor/.gitkeep
Labels: automation

#1 Add include_origin parameter
  .gitignore
  CHANGELOG.asciidoc
  Gemfile.lock
  README.md
  docker/entrypoint.sh
  lib/ecs_logging/logger.rb
  spec/ecs_logging/logger_spec.rb
Labels: apm-ruby

#7 docs: copy paste docs
  .gitignore
  docs/index.asciidoc
  docs/intro.asciidoc
  docs/setup.asciidoc
Labels: agent-ruby, documentation

#9 docs: fix broken include
  docs/setup.asciidoc
Labels: agent-ruby, documentation

#11 Update README.md
  README.md
Labels: agent-ruby, documentation
